name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  MONGO_INITDB_ROOT_USERNAME: "guest"
  MONGO_INITDB_ROOT_PASSWORD: "guest"
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"
    
jobs:
  ci:
    runs-on: ubuntu-latest
          
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run initialization script
        run: |
          chmod +x init.sh
          ./init.sh $MONGODB_CONNECTION_URI $MONGODB_USERNAME $MONGODB_PASSWORD
        env:
          MONGODB_CONNECTION_URI: "mongodb://127.0.0.1:27017"
          MONGODB_USERNAME: "guest"
          MONGODB_PASSWORD: "guest"